/**
 * Task #837 — Verlorene Pflicht-Pausen bei Reopen → Reclose (ArbZG §4 / GoBD).
 *
 * Bug: `generateAutoBreaksForMonth` und der Existenz-Guard in `insertAutoBreaks`
 * fragten `employee_time_entries` OHNE `isNull(deletedAt)`-Filter ab. Beim
 * Wiedereröffnen eines Monats werden die Auto-Pausen nur SOFT-gelöscht
 * (`removeAutoBreaksForMonth`). Beim erneuten Schließen sah der Guard daher die
 * stale, soft-gelöschte Pause als „existiert noch" an und übersprang stillschweigend
 * das Wieder-Anlegen der gesetzlich vorgeschriebenen Pause.
 *
 * Diese Regression treibt den echten Service-Pfad Close → Reopen → Reclose und
 * stellt sicher, dass nach dem erneuten Abschluss wieder eine AKTIVE Auto-Pause
 * existiert.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { and, eq, isNull } from "drizzle-orm";
import { db } from "../server/lib/db";
import { employeeTimeEntries } from "@shared/schema";
import {
  generateAutoBreaksForMonth,
  insertAutoBreaks,
  removeAutoBreaksForMonth,
} from "../server/services/auto-breaks";
import { createTestEmployee, getAuthCookie, runCleanup } from "./test-utils";

let userId: number;
const YEAR = 2090;
const MONTH = 6;
const DATE = `${YEAR}-0${MONTH}-15`;

async function activeAutoBreaks() {
  return db
    .select()
    .from(employeeTimeEntries)
    .where(
      and(
        eq(employeeTimeEntries.userId, userId),
        eq(employeeTimeEntries.entryDate, DATE),
        eq(employeeTimeEntries.entryType, "pause"),
        eq(employeeTimeEntries.isAutoGenerated, true),
        isNull(employeeTimeEntries.deletedAt),
      ),
    );
}

beforeAll(async () => {
  await getAuthCookie();
  const emp = await createTestEmployee({ nachnamePrefix: "AutoBreakReopen" });
  userId = emp.id;

  // 8h reine Arbeitszeit → §4 ArbZG verlangt 30 Min Pause.
  await db.insert(employeeTimeEntries).values([
    {
      userId,
      entryType: "bueroarbeit" as const,
      entryDate: DATE,
      isFullDay: false,
      durationMinutes: 240,
    },
    {
      userId,
      entryType: "bueroarbeit" as const,
      entryDate: DATE,
      isFullDay: false,
      durationMinutes: 240,
    },
  ]);
});

afterAll(async () => {
  // Test-Datensätze des Wegwerf-Users entfernen (hartes Delete, da reiner Testmüll).
  await db.delete(employeeTimeEntries).where(eq(employeeTimeEntries.userId, userId));
  await runCleanup();
});

describe("Auto-Breaks: Reopen → Reclose re-erzeugt die Pflicht-Pause (Task #837)", () => {
  it("legt beim ersten Abschluss eine Auto-Pause an", async () => {
    const breaks = await generateAutoBreaksForMonth(userId, YEAR, MONTH);
    expect(breaks.length).toBeGreaterThan(0);

    const inserted = await db.transaction((tx) => insertAutoBreaks(userId, breaks, tx));
    expect(inserted).toBeGreaterThan(0);

    expect((await activeAutoBreaks()).length).toBe(1);
  });

  it("soft-löscht die Auto-Pause beim Wiedereröffnen", async () => {
    const removed = await removeAutoBreaksForMonth(userId, YEAR, MONTH);
    expect(removed).toBeGreaterThan(0);

    // Keine AKTIVE Auto-Pause mehr — aber die Row existiert noch soft-gelöscht.
    expect((await activeAutoBreaks()).length).toBe(0);
  });

  it("erzeugt beim erneuten Abschluss WIEDER eine aktive Auto-Pause (Kern-Regression)", async () => {
    // Vor dem Fix: generate sah die stale soft-gelöschte Pause als vorhanden an
    // (hasAutoBreak=true) und/oder der insert-Guard übersprang die Neuanlage —
    // die Pflicht-Pause ging verloren.
    const breaks = await generateAutoBreaksForMonth(userId, YEAR, MONTH);
    expect(breaks.length).toBeGreaterThan(0);

    const inserted = await db.transaction((tx) => insertAutoBreaks(userId, breaks, tx));
    expect(inserted).toBeGreaterThan(0);

    expect((await activeAutoBreaks()).length).toBe(1);
  });
});
