uploads = []
generated = []

[[outputs]]
id = "4khVTViufmES48dxOYt2f"
uri = "file://rechnung_RE-2026-0003.pdf"
type = "pdf"
title = "Rechnung RE-2026-0003 (März 2026)"

[[outputs]]
id = "kapYawrd-iFkN_DUuGAVR"
uri = "file://leistungsnachweis_RE-2026-0003.pdf"
type = "pdf"
title = "Leistungsnachweise RE-2026-0003 (März 2026)"

[[outputs]]
id = "qszgiuS3VGaRzQSzTJpvx"
uri = "file://RE-2026-0003.pdf"
type = "pdf"
title = "Rechnung RE-2026-0003 – Layout-Update"

[[outputs]]
id = "2KCqr1ukWoOEUAaNg60uS"
uri = "file://LN-RE-2026-0003.pdf"
type = "pdf"
title = "3 Leistungsnachweise mit Unterschriften – RE-2026-0003"

[[outputs]]
id = "MwYM-mCWzc8KX_abmZ_yl"
uri = "file://LN-RE-2026-0003-neu.pdf"
type = "pdf"
title = "Leistungsnachweise RE-2026-0003 (aktualisiert)"

[[outputs]]
id = "ea938InAlABobCRZ4kMXc"
uri = "file://LN-mit-Unterschriften.pdf"
type = "pdf"
title = "Leistungsnachweise mit sichtbaren Unterschriften (K=Kunde, M=Mitarbeiter)"

[[outputs]]
id = "PXrs7yKKY7zw8fX9lfyzy"
uri = "file://LN-aktuell.pdf"
type = "pdf"
title = "Leistungsnachweise – Anfahrt + Fahrten für/mit Kunde"

[[outputs]]
id = "R5yyjZwWu3KW0jv2F3eNa"
uri = "file://Rechnung-aktuell.pdf"
type = "pdf"
title = "Rechnung – Anfahrt + Fahrten für/mit Kunde"
