import { pgTable, text, integer, serial, boolean, real, index } from "drizzle-orm/pg-core";
import { z } from "zod";
import { timestamp, optionalGermanPhoneSchema, optionalInternationalPhoneSchema } from "./common";
import { users } from "./users";
import { customers } from "./customers";
import { generatedDocuments } from "./documents";

export const companySettings = pgTable("company_settings", {
  id: serial("id").primaryKey(),
  companyName: text("company_name"),
  geschaeftsfuehrer: text("geschaeftsfuehrer"),
  strasse: text("strasse"),
  hausnummer: text("hausnummer"),
  plz: text("plz"),
  stadt: text("stadt"),
  telefon: text("telefon"),
  email: text("email"),
  website: text("website"),
  steuernummer: text("steuernummer"),
  ustId: text("ust_id"),
  iban: text("iban"),
  bic: text("bic"),
  bankName: text("bank_name"),
  ikNummer: text("ik_nummer"),
  logoUrl: text("logo_url"),
  pdfLogoUrl: text("pdf_logo_url"),
  lohnartAlltagsbegleitung: text("lohnart_alltagsbegleitung"),
  lohnartHauswirtschaft: text("lohnart_hauswirtschaft"),
  lohnartUrlaub: text("lohnart_urlaub"),
  lohnartKrankheit: text("lohnart_krankheit"),
  smtpHost: text("smtp_host"),
  smtpPort: text("smtp_port"),
  smtpUser: text("smtp_user"),
  smtpPass: text("smtp_pass"),
  smtpFromEmail: text("smtp_from_email"),
  smtpFromName: text("smtp_from_name"),
  smtpSecure: boolean("smtp_secure").notNull().default(false),
  letterxpressUsername: text("letterxpress_username"),
  letterxpressApiKey: text("letterxpress_api_key"),
  minijobEarningsLimitCents: integer("minijob_earnings_limit_cents").notNull().default(55600),
  letterxpressTestMode: boolean("letterxpress_test_mode").notNull().default(false),
  qontoLogin: text("qonto_login"),
  qontoSecretKey: text("qonto_secret_key"),
  qontoIban: text("qonto_iban"),
  whatsappAccessToken: text("whatsapp_access_token"),
  whatsappPhoneNumberId: text("whatsapp_phone_number_id"),
  whatsappBusinessAccountId: text("whatsapp_business_account_id"),
  whatsappFromOrService: text("whatsapp_from_or_service"),
  whatsappEnabled: boolean("whatsapp_enabled").notNull().default(false),
  twilioAccountSid: text("twilio_account_sid"),
  twilioAuthToken: text("twilio_auth_token"),
  twilioPhoneNumber: text("twilio_phone_number"),
  leadCallBridgePhone: text("lead_call_bridge_phone"),
  leadCallBridgeEnabled: boolean("lead_call_bridge_enabled").notNull().default(false),
  deliveryEmailSubject: text("delivery_email_subject"),
  deliveryCoverLetterText: text("delivery_cover_letter_text"),
  leadAutoReplyEnabled: boolean("lead_auto_reply_enabled").notNull().default(false),
  leadAutoReplySubject: text("lead_auto_reply_subject"),
  leadAutoReplyBody: text("lead_auto_reply_body"),
  leadAutoReplyAttachmentPath: text("lead_auto_reply_attachment_path"),
  leadAutoReplyAttachmentName: text("lead_auto_reply_attachment_name"),
  latitude: real("latitude"),
  longitude: real("longitude"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  updatedByUserId: integer("updated_by_user_id").references(() => users.id),
});

export type CompanySettings = typeof companySettings.$inferSelect;

export const updateCompanySettingsSchema = z.object({
  companyName: z.string().optional(),
  geschaeftsfuehrer: z.string().optional(),
  strasse: z.string().optional(),
  hausnummer: z.string().optional(),
  plz: z.string().optional(),
  stadt: z.string().optional(),
  telefon: optionalGermanPhoneSchema,
  email: z.string().optional(),
  website: z.string().optional().nullable(),
  steuernummer: z.string().optional(),
  ustId: z.string().optional().nullable(),
  iban: z.string().optional(),
  bic: z.string().optional(),
  bankName: z.string().optional(),
  ikNummer: z.string().optional(),
  logoUrl: z.string().optional().nullable(),
  pdfLogoUrl: z.string().optional().nullable(),
  lohnartAlltagsbegleitung: z.string().optional().nullable(),
  lohnartHauswirtschaft: z.string().optional().nullable(),
  lohnartUrlaub: z.string().optional().nullable(),
  lohnartKrankheit: z.string().optional().nullable(),
  smtpHost: z.string().optional().nullable(),
  smtpPort: z.string().optional().nullable(),
  smtpUser: z.string().optional().nullable(),
  smtpPass: z.string().optional().nullable(),
  smtpFromEmail: z.string().optional().nullable(),
  smtpFromName: z.string().optional().nullable(),
  smtpSecure: z.boolean().optional(),
  letterxpressUsername: z.string().optional().nullable(),
  letterxpressApiKey: z.string().optional().nullable(),
  minijobEarningsLimitCents: z.number().int().min(0, "Betrag darf nicht negativ sein").optional(),
  letterxpressTestMode: z.boolean().optional(),
  qontoLogin: z.string().optional().nullable(),
  qontoSecretKey: z.string().optional().nullable(),
  qontoIban: z.string().optional().nullable(),
  whatsappAccessToken: z.string().optional().nullable(),
  whatsappPhoneNumberId: z.string().optional().nullable(),
  whatsappBusinessAccountId: z.string().optional().nullable(),
  whatsappFromOrService: z.string().optional().nullable(),
  whatsappEnabled: z.boolean().optional(),
  twilioAccountSid: z.string().optional().nullable(),
  twilioAuthToken: z.string().optional().nullable(),
  twilioPhoneNumber: optionalInternationalPhoneSchema,
  leadCallBridgePhone: optionalInternationalPhoneSchema,
  leadCallBridgeEnabled: z.boolean().optional(),
  deliveryEmailSubject: z.string().optional().nullable(),
  deliveryCoverLetterText: z.string().optional().nullable(),
  leadAutoReplyEnabled: z.boolean().optional(),
  leadAutoReplySubject: z.string().optional().nullable(),
  leadAutoReplyBody: z.string().optional().nullable(),
  leadAutoReplyAttachmentPath: z.string().optional().nullable(),
  leadAutoReplyAttachmentName: z.string().optional().nullable(),
});

export type UpdateCompanySettings = z.infer<typeof updateCompanySettingsSchema>;

export const documentDeliveries = pgTable("document_deliveries", {
  id: serial("id").primaryKey(),
  customerId: integer("customer_id").references(() => customers.id),
  generatedDocumentId: integer("generated_document_id").references(() => generatedDocuments.id),
  deliveryMethod: text("delivery_method").notNull(),
  status: text("status").notNull().default("pending"),
  recipientEmail: text("recipient_email"),
  recipientName: text("recipient_name"),
  recipientAddress: text("recipient_address"),
  letterxpressLetterId: text("letterxpress_letter_id"),
  errorMessage: text("error_message"),
  documentFileNames: text("document_file_names"),
  sentAt: timestamp("sent_at"),
  deliveredAt: timestamp("delivered_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdByUserId: integer("created_by_user_id").references(() => users.id),
}, (table) => [
  index("doc_deliveries_customer_idx").on(table.customerId),
  index("doc_deliveries_document_idx").on(table.generatedDocumentId),
  index("doc_deliveries_status_idx").on(table.status),
]);

export type DocumentDelivery = typeof documentDeliveries.$inferSelect;
export type InsertDocumentDelivery = typeof documentDeliveries.$inferInsert;
