import { pgTable, text, integer, serial, boolean } from "drizzle-orm/pg-core";
import { z } from "zod";
import { timestamp } from "./common";
import { users } from "./users";

export const companySettings = pgTable("company_settings", {
  id: serial("id").primaryKey(),
  companyName: text("company_name"),
  geschaeftsfuehrer: text("geschaeftsfuehrer"),
  strasse: text("strasse"),
  hausnummer: text("hausnummer"),
  plz: text("plz"),
  stadt: text("stadt"),
  telefon: text("telefon"),
  email: text("email"),
  website: text("website"),
  steuernummer: text("steuernummer"),
  ustId: text("ust_id"),
  iban: text("iban"),
  bic: text("bic"),
  bankName: text("bank_name"),
  ikNummer: text("ik_nummer"),
  anerkennungsnummer45a: text("anerkennungsnummer_45a"),
  anerkennungsBundesland: text("anerkennungs_bundesland"),
  logoUrl: text("logo_url"),
  lohnartAlltagsbegleitung: text("lohnart_alltagsbegleitung"),
  lohnartHauswirtschaft: text("lohnart_hauswirtschaft"),
  lohnartUrlaub: text("lohnart_urlaub"),
  lohnartKrankheit: text("lohnart_krankheit"),
  smtpHost: text("smtp_host"),
  smtpPort: text("smtp_port"),
  smtpUser: text("smtp_user"),
  smtpPass: text("smtp_pass"),
  smtpFromEmail: text("smtp_from_email"),
  smtpFromName: text("smtp_from_name"),
  smtpSecure: boolean("smtp_secure").notNull().default(false),
  epostVendorId: text("epost_vendor_id"),
  epostEkp: text("epost_ekp"),
  epostPassword: text("epost_password"),
  epostSalt: text("epost_salt"),
  epostTestMode: boolean("epost_test_mode").notNull().default(true),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  updatedByUserId: integer("updated_by_user_id").references(() => users.id),
});

export type CompanySettings = typeof companySettings.$inferSelect;

export const updateCompanySettingsSchema = z.object({
  companyName: z.string().optional(),
  geschaeftsfuehrer: z.string().optional(),
  strasse: z.string().optional(),
  hausnummer: z.string().optional(),
  plz: z.string().optional(),
  stadt: z.string().optional(),
  telefon: z.string().optional(),
  email: z.string().optional(),
  website: z.string().optional().nullable(),
  steuernummer: z.string().optional(),
  ustId: z.string().optional().nullable(),
  iban: z.string().optional(),
  bic: z.string().optional(),
  bankName: z.string().optional(),
  ikNummer: z.string().optional(),
  anerkennungsnummer45a: z.string().optional(),
  anerkennungsBundesland: z.string().optional(),
  logoUrl: z.string().optional().nullable(),
  lohnartAlltagsbegleitung: z.string().optional().nullable(),
  lohnartHauswirtschaft: z.string().optional().nullable(),
  lohnartUrlaub: z.string().optional().nullable(),
  lohnartKrankheit: z.string().optional().nullable(),
  smtpHost: z.string().optional().nullable(),
  smtpPort: z.string().optional().nullable(),
  smtpUser: z.string().optional().nullable(),
  smtpPass: z.string().optional().nullable(),
  smtpFromEmail: z.string().optional().nullable(),
  smtpFromName: z.string().optional().nullable(),
  smtpSecure: z.boolean().optional(),
  epostVendorId: z.string().optional().nullable(),
  epostEkp: z.string().optional().nullable(),
  epostPassword: z.string().optional().nullable(),
  epostSalt: z.string().optional().nullable(),
  epostTestMode: z.boolean().optional(),
});

export type UpdateCompanySettings = z.infer<typeof updateCompanySettingsSchema>;

export const documentDeliveries = pgTable("document_deliveries", {
  id: serial("id").primaryKey(),
  customerId: integer("customer_id"),
  generatedDocumentId: integer("generated_document_id"),
  deliveryMethod: text("delivery_method").notNull(),
  status: text("status").notNull().default("pending"),
  recipientEmail: text("recipient_email"),
  recipientName: text("recipient_name"),
  recipientAddress: text("recipient_address"),
  epostLetterId: text("epost_letter_id"),
  errorMessage: text("error_message"),
  documentFileNames: text("document_file_names"),
  sentAt: timestamp("sent_at"),
  deliveredAt: timestamp("delivered_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdByUserId: integer("created_by_user_id").references(() => users.id),
});

export type DocumentDelivery = typeof documentDeliveries.$inferSelect;
export type InsertDocumentDelivery = typeof documentDeliveries.$inferInsert;
