import { pgTable, text, integer, serial, time, date, boolean, unique, index } from "drizzle-orm/pg-core";
import { z } from "zod";
import { timestamp } from "./common";
import { users } from "./users";

// ============================================
// EMPLOYEE TIME TRACKING
// Migration SQL:
// ALTER TABLE employee_time_entries ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
// ============================================

// Time entry types for non-client work
export const TIME_ENTRY_TYPES = [
  "urlaub",        // Vacation
  "krankheit",     // Sick leave
  "pause",         // Break
  "bueroarbeit",   // Office/admin work
  "vertrieb",      // Sales
  "schulung",      // Training
  "besprechung",   // Meeting
  "sonstiges",     // Other
  "verfuegbar",    // Available (organizational only, not counted as work time)
] as const;

export type TimeEntryType = typeof TIME_ENTRY_TYPES[number];

// Employee time entries table
export const employeeTimeEntries = pgTable("employee_time_entries", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  entryType: text("entry_type").notNull(), // TimeEntryType
  entryDate: date("entry_date").notNull(),
  startTime: time("start_time"), // Optional for full-day entries like vacation
  endTime: time("end_time"),     // Optional for full-day entries
  isFullDay: boolean("is_full_day").notNull().default(false),
  durationMinutes: integer("duration_minutes"), // Calculated or manual for breaks
  kilometers: integer("kilometers").default(0),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),
}, (table) => [
  index("time_entries_user_id_idx").on(table.userId),
  index("time_entries_entry_date_idx").on(table.entryDate),
  index("time_entries_user_date_idx").on(table.userId, table.entryDate),
]);

// Employee vacation allowance per year
export const employeeVacationAllowance = pgTable("employee_vacation_allowance", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  year: integer("year").notNull(),
  totalDays: integer("total_days").notNull().default(30), // Standard German vacation days
  carryOverDays: integer("carry_over_days").notNull().default(0), // Days carried from previous year
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => [
  unique("user_year_unique").on(table.userId, table.year),
]);

// Insert schemas
export const insertTimeEntrySchema = z.object({
  entryType: z.enum(TIME_ENTRY_TYPES),
  entryDate: z.string().min(1, "Datum ist erforderlich"),
  startTime: z.string().optional().nullable(),
  endTime: z.string().optional().nullable(),
  isFullDay: z.boolean().optional().default(false),
  durationMinutes: z.number().optional().nullable(),
  kilometers: z.number().min(0, "Kilometer dürfen nicht negativ sein").optional().nullable(),
  notes: z.string().max(500, "Maximal 500 Zeichen").optional().nullable(),
});

export const updateTimeEntrySchema = insertTimeEntrySchema.partial();

export const insertVacationAllowanceSchema = z.object({
  userId: z.number(),
  year: z.number().min(2020, "Jahr muss zwischen 2020 und 2100 liegen").max(2100, "Jahr muss zwischen 2020 und 2100 liegen"),
  totalDays: z.number().min(0, "Urlaubstage dürfen nicht negativ sein").max(365, "Maximal 365 Tage").default(30),
  carryOverDays: z.number().min(0, "Übertragstage dürfen nicht negativ sein").max(365, "Maximal 365 Tage").default(0),
  notes: z.string().max(500, "Maximal 500 Zeichen").optional().nullable(),
});

export type EmployeeTimeEntry = typeof employeeTimeEntries.$inferSelect;
export type InsertTimeEntry = z.infer<typeof insertTimeEntrySchema>;
export type UpdateTimeEntry = z.infer<typeof updateTimeEntrySchema>;

export type EmployeeVacationAllowance = typeof employeeVacationAllowance.$inferSelect;
export type InsertVacationAllowance = z.infer<typeof insertVacationAllowanceSchema>;
