import { pgTable, text, integer, numeric, real, serial, time, date, boolean, unique, index } from "drizzle-orm/pg-core";
import { z } from "zod";
import { timestamp } from "./common";
import { users } from "./users";

// ============================================
// EMPLOYEE TIME TRACKING
// Migration SQL:
// ALTER TABLE employee_time_entries ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
// ============================================

// Time entry types for non-client work
export const TIME_ENTRY_TYPES = [
  "urlaub",        // Vacation
  "krankheit",     // Sick leave
  "pause",         // Break
  "bueroarbeit",   // Office/admin work
  "vertrieb",      // Sales
  "sonstiges",     // Other (covers former 'schulung' and 'besprechung')
  "verfuegbar",    // Available (organizational only, not counted as work time)
  "blocker",       // Blocked time (no appointments allowed, not counted as work time)
] as const;

export type TimeEntryType = typeof TIME_ENTRY_TYPES[number];

// Employee time entries table
export const employeeTimeEntries = pgTable("employee_time_entries", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  entryType: text("entry_type").notNull(), // TimeEntryType
  entryDate: date("entry_date").notNull(),
  startTime: time("start_time"), // Optional for full-day entries like vacation
  endTime: time("end_time"),     // Optional for full-day entries
  isFullDay: boolean("is_full_day").notNull().default(false),
  durationMinutes: integer("duration_minutes"), // Calculated or manual for breaks
  kilometers: real("kilometers").default(0),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  deletedAt: timestamp("deleted_at"),
}, (table) => [
  index("time_entries_user_id_idx").on(table.userId),
  index("time_entries_entry_date_idx").on(table.entryDate),
  index("time_entries_user_date_idx").on(table.userId, table.entryDate),
]);

// Employee vacation allowance per year
// totalDays als numeric(5,2) damit anteilige Werte (z. B. 11.33 nach unterjähriger
// Anspruchsänderung — siehe `vacationEntitlementHistory`) sauber abgebildet werden.
export const employeeVacationAllowance = pgTable("employee_vacation_allowance", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  year: integer("year").notNull(),
  totalDays: numeric("total_days", { precision: 5, scale: 2 }).notNull().default("30"),
  carryOverDays: integer("carry_over_days").notNull().default(0), // Days carried from previous year
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => [
  unique("user_year_unique").on(table.userId, table.year),
]);

// Historie des Jahresurlaubsanspruchs pro Mitarbeiter — wird benötigt, damit
// unterjährige Änderungen am `vacationDaysPerYear` anteilig (monatsgenau) in den
// Jahresanspruch einfließen, statt rückwirkend für das gesamte Jahr zu greifen.
export const vacationEntitlementHistory = pgTable("vacation_entitlement_history", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  validFromYear: integer("valid_from_year").notNull(),
  validFromMonth: integer("valid_from_month").notNull(), // 1-12
  daysPerYear: integer("days_per_year").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: integer("created_by").references(() => users.id),
}, (table) => [
  unique("vacation_entitlement_history_unique").on(table.userId, table.validFromYear, table.validFromMonth),
  index("vacation_entitlement_history_user_idx").on(table.userId),
]);

// Insert schemas
export const insertTimeEntrySchema = z.object({
  entryType: z.enum(TIME_ENTRY_TYPES),
  entryDate: z.string().min(1, "Datum ist erforderlich"),
  startTime: z.string().optional().nullable(),
  endTime: z.string().optional().nullable(),
  isFullDay: z.boolean().optional().default(false),
  durationMinutes: z.number().optional().nullable(),
  kilometers: z.number().min(0, "Kilometer dürfen nicht negativ sein").optional().nullable(),
  notes: z.string().max(500, "Maximal 500 Zeichen").optional().nullable(),
});

export const updateTimeEntrySchema = insertTimeEntrySchema.partial();

export const insertVacationAllowanceSchema = z.object({
  userId: z.number(),
  year: z.number().min(2020, "Jahr muss zwischen 2020 und 2100 liegen").max(2100, "Jahr muss zwischen 2020 und 2100 liegen"),
  totalDays: z.number().min(0, "Urlaubstage dürfen nicht negativ sein").max(365, "Maximal 365 Tage").default(30),
  carryOverDays: z.number().min(0, "Übertragstage dürfen nicht negativ sein").max(365, "Maximal 365 Tage").default(0),
  notes: z.string().max(500, "Maximal 500 Zeichen").optional().nullable(),
});

export const insertVacationEntitlementHistorySchema = z.object({
  userId: z.number(),
  validFromYear: z.number().int().min(2020).max(2100),
  validFromMonth: z.number().int().min(1).max(12),
  daysPerYear: z.number().int().min(0).max(365),
  createdBy: z.number().nullable().optional(),
});

export type EmployeeTimeEntry = typeof employeeTimeEntries.$inferSelect;
export type InsertTimeEntry = z.infer<typeof insertTimeEntrySchema>;
export type UpdateTimeEntry = z.infer<typeof updateTimeEntrySchema>;

// Drizzles `numeric`-Typ liefert in TS einen `string`. Das Storage-Layer
// (`server/storage/time-tracking/vacation.ts`) konvertiert beim Lesen auf
// `number`, sodass alle Aufrufer mit Zahlen arbeiten.
export type EmployeeVacationAllowance = typeof employeeVacationAllowance.$inferSelect;
export type InsertVacationAllowance = z.infer<typeof insertVacationAllowanceSchema>;

export type VacationEntitlementHistory = typeof vacationEntitlementHistory.$inferSelect;
export type InsertVacationEntitlementHistory = z.infer<typeof insertVacationEntitlementHistorySchema>;
