import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { formatDateForDisplay } from "@shared/utils/datetime";
import { iconSize } from "@/design-system";
import { StatusBadge } from "@/components/patterns/status-badge";
import { Users, Unlock, Plus, Pencil, Trash2, Lock, Settings } from "lucide-react";
import type { TimeEntryType, TimeEntryWithUser } from "@/lib/api/types";
import { TIME_ENTRY_TYPE_CONFIG } from "@/features/time-tracking/constants";

interface EmployeeTimeCardProps {
  employeeName: string;
  employeeEntries: TimeEntryWithUser[];
  employeeId?: number;
  isClosed: boolean;
  onCloseMonth: (userId: number, userName: string) => void;
  onReopenMonth: (userId: number, userName: string) => void;
  onAddEntry: (userId: number, userName: string) => void;
  onEditVacation: (userId: number, userName: string) => void;
  onEditEntry: (entry: TimeEntryWithUser) => void;
  onDeleteEntry: (id: number, label: string) => void;
}

export function EmployeeTimeCard({
  employeeName,
  employeeEntries,
  employeeId,
  isClosed,
  onCloseMonth,
  onReopenMonth,
  onAddEntry,
  onEditVacation,
  onEditEntry,
  onDeleteEntry,
}: EmployeeTimeCardProps) {
  return (
    <Card>
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <CardTitle className="text-lg flex items-center gap-2">
            <Users className={iconSize.md} />
            {employeeName}
            {isClosed && <StatusBadge type="month" value="closed" size="sm" />}
          </CardTitle>
          <div className="flex items-center gap-1 flex-wrap">
            {employeeId && !isClosed && (
              <Button
                variant="ghost"
                size="sm"
                className="text-teal-700 hover:text-teal-800 hover:bg-teal-50"
                onClick={() => onCloseMonth(employeeId, employeeName)}
                data-testid={`button-close-month-${employeeId}`}
              >
                <Lock className={`${iconSize.sm} mr-1`} />
                Abschließen
              </Button>
            )}
            {employeeId && isClosed && (
              <Button
                variant="ghost"
                size="sm"
                className="text-amber-700 hover:text-amber-800 hover:bg-amber-50"
                onClick={() => onReopenMonth(employeeId, employeeName)}
                data-testid={`button-reopen-month-${employeeId}`}
              >
                <Unlock className={`${iconSize.sm} mr-1`} />
                Wiedereröffnen
              </Button>
            )}
            {employeeId && (
              <Button
                variant="ghost"
                size="sm"
                className="text-blue-700 hover:text-blue-800 hover:bg-blue-50"
                onClick={() => onAddEntry(employeeId, employeeName)}
                data-testid={`button-add-entry-${employeeId}`}
              >
                <Plus className={`${iconSize.sm} mr-1`} />
                Eintrag
              </Button>
            )}
            {employeeId && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => onEditVacation(employeeId, employeeName)}
                data-testid={`button-edit-vacation-${employeeId}`}
              >
                <Settings className={`${iconSize.sm} mr-1`} />
                Urlaubskontingent
              </Button>
            )}
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {employeeEntries.length === 0 ? (
          <p className="text-sm text-gray-500">Keine Zeiteinträge in diesem Monat.</p>
        ) : (
          <div className="space-y-2">
            {[...employeeEntries]
              .sort((a, b) => a.entryDate.localeCompare(b.entryDate))
              .map((entry) => {
                const config = TIME_ENTRY_TYPE_CONFIG[entry.entryType as TimeEntryType];
                const Icon = config.icon;
                const isAutoGenerated = (entry as any).isAutoGenerated;
                return (
                  <div
                    key={entry.id}
                    className={`p-3 rounded-lg ${config.bgColor} flex items-center justify-between group`}
                    data-testid={`time-entry-${entry.id}`}
                  >
                    <div className="flex items-center gap-3 min-w-0 flex-1">
                      <Icon className={`${iconSize.md} ${config.color} shrink-0`} />
                      <div className="min-w-0">
                        <div className={`font-medium ${config.color} flex items-center gap-2`}>
                          {config.label}
                          {isAutoGenerated && (
                            <span className="text-xs bg-gray-200 text-gray-600 px-1.5 py-0.5 rounded">Auto</span>
                          )}
                        </div>
                        <div className="text-sm text-gray-600">
                          {formatDateForDisplay(entry.entryDate, { weekday: "short", day: "numeric", month: "short" })}
                          {entry.startTime && entry.endTime && (
                            <span className="ml-2">
                              {entry.startTime.slice(0, 5)} - {entry.endTime.slice(0, 5)}
                            </span>
                          )}
                          {entry.isFullDay && <span className="ml-2">(Ganztägig)</span>}
                        </div>
                        {entry.notes && (
                          <div className="text-xs text-gray-500 truncate mt-0.5">{entry.notes}</div>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 group-focus-within:opacity-100 transition-opacity shrink-0">
                      {!isAutoGenerated && (
                        <>
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => onEditEntry(entry)}
                            aria-label="Bearbeiten"
                            data-testid={`button-edit-entry-${entry.id}`}
                          >
                            <Pencil className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="text-red-600 hover:text-red-700 hover:bg-red-50"
                            onClick={() => onDeleteEntry(
                              entry.id,
                              `${config.label} am ${formatDateForDisplay(entry.entryDate, { day: "numeric", month: "short" })}`,
                            )}
                            aria-label="Löschen"
                            data-testid={`button-delete-entry-${entry.id}`}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </>
                      )}
                    </div>
                  </div>
                );
              })}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
