import { eq, and, gte, lte, inArray, isNull, sql } from "drizzle-orm";
import {
  employeeTimeEntries,
  systemSettings,
  appointments,
} from "@shared/schema";
import { db, type DbOrTx } from "../lib/db";
import {
  getEntryDuration,
  calculateRequiredBreak,
  isWorkEntryType,
  ARBZG_MAX_DAILY_MINUTES,
} from "@shared/domain/time-entries";
import { employeeWorkedAppointmentsFilter } from "../storage/appointment-helpers";
import { appointmentsRepo, employeeTimeEntriesRepo } from "../repos";

interface AutoBreakResult {
  date: string;
  totalWorkMinutes: number;
  existingBreakMinutes: number;
  requiredBreakMinutes: number;
  autoBreakMinutes: number;
}

async function isAutoBreaksEnabled(): Promise<boolean> {
  const rows = await db.select().from(systemSettings).limit(1);
  if (rows.length === 0) return true;
  return rows[0].autoBreaksEnabled;
}

export async function generateAutoBreaksForMonth(
  userId: number,
  year: number,
  month: number
): Promise<AutoBreakResult[]> {
  const enabled = await isAutoBreaksEnabled();
  if (!enabled) return [];

  const monthStr = month.toString().padStart(2, "0");
  const startDate = `${year}-${monthStr}-01`;
  const lastDay = new Date(year, month, 0).getDate();
  const endDate = `${year}-${monthStr}-${lastDay.toString().padStart(2, "0")}`;

  const [employeeAppointments, timeEntries] = await Promise.all([
    appointmentsRepo.selectFrom(db)
      .where(
        and(
          employeeWorkedAppointmentsFilter(userId),
          gte(appointments.date, startDate),
          lte(appointments.date, endDate),
          isNull(appointments.deletedAt)
        )
      ),
    employeeTimeEntriesRepo.selectFrom(db)
      .where(
        and(
          eq(employeeTimeEntries.userId, userId),
          gte(employeeTimeEntries.entryDate, startDate),
          lte(employeeTimeEntries.entryDate, endDate)
        )
      ),
  ]);

  const workByDate: Record<
    string,
    { workMinutes: number; breakMinutes: number; hasAutoBreak: boolean }
  > = {};

  for (const appt of employeeAppointments) {
    if (appt.status === "completed" || appt.status === "documenting") {
      const date = appt.date;
      if (!workByDate[date])
        workByDate[date] = { workMinutes: 0, breakMinutes: 0, hasAutoBreak: false };
      workByDate[date].workMinutes += appt.durationPromised || 0;
    }
  }

  for (const entry of timeEntries) {
    const date = entry.entryDate;
    if (!workByDate[date])
      workByDate[date] = { workMinutes: 0, breakMinutes: 0, hasAutoBreak: false };

    const duration = getEntryDuration(entry);

    if (entry.entryType === "pause") {
      workByDate[date].breakMinutes += duration;
      if (entry.isAutoGenerated) {
        workByDate[date].hasAutoBreak = true;
      }
    } else if (isWorkEntryType(entry.entryType)) {
      workByDate[date].workMinutes += duration;
    }
  }

  const results: AutoBreakResult[] = [];

  for (const [date, data] of Object.entries(workByDate)) {
    const required = calculateRequiredBreak(data.workMinutes);
    if (required <= 0) continue;

    const missing = Math.max(0, required - data.breakMinutes);
    if (missing <= 0) continue;

    if (data.hasAutoBreak) continue;

    results.push({
      date,
      totalWorkMinutes: data.workMinutes,
      existingBreakMinutes: data.breakMinutes,
      requiredBreakMinutes: required,
      autoBreakMinutes: missing,
    });
  }

  results.sort((a, b) => a.date.localeCompare(b.date));
  return results;
}

export async function insertAutoBreaks(
  userId: number,
  breaks: AutoBreakResult[],
  txOrDb: DbOrTx = db
): Promise<number> {
  if (breaks.length === 0) return 0;

  const allDates = breaks.map((b) => b.date);
  const existingAutoBreaks = await employeeTimeEntriesRepo.selectColumnsFrom({ entryDate: employeeTimeEntries.entryDate }, txOrDb)
    .where(
      and(
        eq(employeeTimeEntries.userId, userId),
        eq(employeeTimeEntries.entryType, "pause"),
        eq(employeeTimeEntries.isAutoGenerated, true),
        inArray(employeeTimeEntries.entryDate, allDates)
      )
    );

  const existingDates = new Set(existingAutoBreaks.map((e) => e.entryDate));

  const toInsert = breaks.filter((b) => !existingDates.has(b.date));
  if (toInsert.length === 0) return 0;

  await txOrDb.insert(employeeTimeEntries).values(
    toInsert.map((b) => ({
      userId,
      entryType: "pause" as const,
      entryDate: b.date,
      isFullDay: false,
      durationMinutes: b.autoBreakMinutes,
      isAutoGenerated: true,
      notes: `Automatische Pause gem. §4 ArbZG (${b.autoBreakMinutes} Min. bei ${Math.round((b.totalWorkMinutes / 60) * 10) / 10}h Arbeitszeit)`,
    }))
  );

  return toInsert.length;
}

export async function previewAutoBreaksForMonth(
  userId: number,
  year: number,
  month: number
): Promise<AutoBreakResult[]> {
  return generateAutoBreaksForMonth(userId, year, month);
}

export async function removeAutoBreaksForMonth(
  userId: number,
  year: number,
  month: number
): Promise<number> {
  const monthStr = month.toString().padStart(2, "0");
  const startDate = `${year}-${monthStr}-01`;
  const lastDay = new Date(year, month, 0).getDate();
  const endDate = `${year}-${monthStr}-${lastDay.toString().padStart(2, "0")}`;

  const deleted = await db
    .update(employeeTimeEntries)
    .set({ deletedAt: new Date() })
    .where(
      and(
        eq(employeeTimeEntries.userId, userId),
        gte(employeeTimeEntries.entryDate, startDate),
        lte(employeeTimeEntries.entryDate, endDate),
        eq(employeeTimeEntries.entryType, "pause"),
        eq(employeeTimeEntries.isAutoGenerated, true),
        sql`${employeeTimeEntries.deletedAt} IS NULL`
      )
    )
    .returning();

  return deleted.length;
}

async function fetchDayData(userId: number, date: string) {
  const [dayAppointments, dayEntries] = await Promise.all([
    appointmentsRepo.selectFrom(db)
      .where(
        and(
          employeeWorkedAppointmentsFilter(userId),
          eq(appointments.date, date),
          isNull(appointments.deletedAt)
        )
      ),
    employeeTimeEntriesRepo.selectFrom(db)
      .where(
        and(
          eq(employeeTimeEntries.userId, userId),
          eq(employeeTimeEntries.entryDate, date),
          isNull(employeeTimeEntries.deletedAt)
        )
      ),
  ]);
  return { dayAppointments, dayEntries };
}

function sumAppointmentWork(dayAppointments: { status: string; durationPromised: number | null }[]): number {
  let minutes = 0;
  for (const appt of dayAppointments) {
    if (appt.status === "completed" || appt.status === "documenting") {
      minutes += appt.durationPromised || 0;
    }
  }
  return minutes;
}

export async function checkAndRecalcDailyAutoBreak(
  userId: number,
  date: string
): Promise<void> {
  try {
    const enabled = await isAutoBreaksEnabled();
    if (!enabled) return;

    const { dayAppointments, dayEntries } = await fetchDayData(userId, date);

    let workMinutes = sumAppointmentWork(dayAppointments);
    let manualBreakMinutes = 0;

    for (const entry of dayEntries) {
      if (entry.isAutoGenerated) continue;
      const duration = getEntryDuration(entry);
      if (entry.entryType === "pause") {
        manualBreakMinutes += duration;
      } else if (isWorkEntryType(entry.entryType)) {
        workMinutes += duration;
      }
    }

    const requiredBreak = calculateRequiredBreak(workMinutes);
    const missingBreak = Math.max(0, requiredBreak - manualBreakMinutes);

    const existingAutoBreak = dayEntries.find(
      (e) => e.entryType === "pause" && e.isAutoGenerated
    );

    if (missingBreak <= 0) {
      if (existingAutoBreak) {
        await db
          .update(employeeTimeEntries)
          .set({ deletedAt: new Date() })
          .where(eq(employeeTimeEntries.id, existingAutoBreak.id));
      }
      return;
    }

    if (existingAutoBreak) {
      if (existingAutoBreak.durationMinutes !== missingBreak) {
        await db
          .update(employeeTimeEntries)
          .set({
            durationMinutes: missingBreak,
            notes: `Automatische Pause gem. §4 ArbZG (${missingBreak} Min. bei ${Math.round((workMinutes / 60) * 10) / 10}h Arbeitszeit)`,
            updatedAt: new Date(),
          })
          .where(eq(employeeTimeEntries.id, existingAutoBreak.id));
      }
    } else {
      await db.insert(employeeTimeEntries).values({
        userId,
        entryType: "pause" as const,
        entryDate: date,
        isFullDay: false,
        durationMinutes: missingBreak,
        isAutoGenerated: true,
        notes: `Automatische Pause gem. §4 ArbZG (${missingBreak} Min. bei ${Math.round((workMinutes / 60) * 10) / 10}h Arbeitszeit)`,
      });
    }
  } catch (err) {
    console.error(`[auto-breaks] Fehler bei täglicher Pausenberechnung für User ${userId}, Datum ${date}:`, err);
  }
}

export async function checkDailyMaximum(
  userId: number,
  date: string,
  excludeEntryId?: number
): Promise<{ warning: string; totalMinutes: number } | null> {
  const { dayAppointments, dayEntries } = await fetchDayData(userId, date);

  let workMinutes = sumAppointmentWork(dayAppointments);

  for (const entry of dayEntries) {
    if (entry.id === excludeEntryId) continue;
    if (entry.entryType === "pause") continue;
    if (isWorkEntryType(entry.entryType)) {
      workMinutes += getEntryDuration(entry);
    }
  }

  if (workMinutes > ARBZG_MAX_DAILY_MINUTES) {
    const hours = Math.round((workMinutes / 60) * 10) / 10;
    return {
      warning: `Achtung: Die tägliche Arbeitszeit beträgt ${hours}h und überschreitet das Maximum von 10h gemäß §3 ArbZG.`,
      totalMinutes: workMinutes,
    };
  }

  return null;
}
