import { eq, and, gte, lte, inArray, sql } from "drizzle-orm";
import {
  employeeTimeEntries,
  systemSettings,
  appointments,
} from "@shared/schema";
import { timeTrackingStorage } from "../storage/time-tracking";
import { db, type DbOrTx } from "../lib/db";

export interface AutoBreakResult {
  date: string;
  totalWorkMinutes: number;
  existingBreakMinutes: number;
  requiredBreakMinutes: number;
  autoBreakMinutes: number;
}

function calculateRequiredBreak(workMinutes: number): number {
  if (workMinutes > 540) return 45; // > 9h
  if (workMinutes > 360) return 30; // > 6h
  return 0;
}

async function isAutoBreaksEnabled(): Promise<boolean> {
  const rows = await db.select().from(systemSettings).limit(1);
  if (rows.length === 0) return true;
  return rows[0].autoBreaksEnabled;
}

export async function generateAutoBreaksForMonth(
  userId: number,
  year: number,
  month: number
): Promise<AutoBreakResult[]> {
  const enabled = await isAutoBreaksEnabled();
  if (!enabled) return [];

  const monthStr = month.toString().padStart(2, "0");
  const startDate = `${year}-${monthStr}-01`;
  const lastDay = new Date(year, month, 0).getDate();
  const endDate = `${year}-${monthStr}-${lastDay.toString().padStart(2, "0")}`;

  const [employeeAppointments, timeEntries] = await Promise.all([
    timeTrackingStorage.getEmployeeAppointments(userId, startDate, endDate),
    db
      .select()
      .from(employeeTimeEntries)
      .where(
        and(
          eq(employeeTimeEntries.userId, userId),
          gte(employeeTimeEntries.entryDate, startDate),
          lte(employeeTimeEntries.entryDate, endDate)
        )
      ),
  ]);

  const workByDate: Record<
    string,
    { workMinutes: number; breakMinutes: number; hasAutoBreak: boolean }
  > = {};

  for (const appt of employeeAppointments) {
    if (appt.status === "completed" || appt.status === "documenting") {
      const date = appt.date;
      if (!workByDate[date])
        workByDate[date] = { workMinutes: 0, breakMinutes: 0, hasAutoBreak: false };
      workByDate[date].workMinutes += appt.durationPromised || 0;
    }
  }

  const getEntryDuration = (entry: {
    durationMinutes: number | null;
    startTime: string | null;
    endTime: string | null;
  }): number => {
    if (entry.durationMinutes && entry.durationMinutes > 0)
      return entry.durationMinutes;
    if (entry.startTime && entry.endTime) {
      const [startH, startM] = entry.startTime.split(":").map(Number);
      const [endH, endM] = entry.endTime.split(":").map(Number);
      return Math.max(0, endH * 60 + endM - (startH * 60 + startM));
    }
    return 0;
  };

  for (const entry of timeEntries) {
    const date = entry.entryDate;
    if (!workByDate[date])
      workByDate[date] = { workMinutes: 0, breakMinutes: 0, hasAutoBreak: false };

    const duration = getEntryDuration(entry);

    if (entry.entryType === "pause") {
      workByDate[date].breakMinutes += duration;
      if (entry.isAutoGenerated) {
        workByDate[date].hasAutoBreak = true;
      }
    } else if (
      ["bueroarbeit", "vertrieb", "schulung", "besprechung", "sonstiges"].includes(
        entry.entryType
      )
    ) {
      workByDate[date].workMinutes += duration;
    }
  }

  const results: AutoBreakResult[] = [];

  for (const [date, data] of Object.entries(workByDate)) {
    const required = calculateRequiredBreak(data.workMinutes);
    if (required <= 0) continue;

    const missing = Math.max(0, required - data.breakMinutes);
    if (missing <= 0) continue;

    if (data.hasAutoBreak) continue;

    results.push({
      date,
      totalWorkMinutes: data.workMinutes,
      existingBreakMinutes: data.breakMinutes,
      requiredBreakMinutes: required,
      autoBreakMinutes: missing,
    });
  }

  results.sort((a, b) => a.date.localeCompare(b.date));
  return results;
}

export async function insertAutoBreaks(
  userId: number,
  breaks: AutoBreakResult[],
  txOrDb: DbOrTx = db
): Promise<number> {
  if (breaks.length === 0) return 0;

  const allDates = breaks.map((b) => b.date);
  const existingAutoBreaks = await txOrDb
    .select({ entryDate: employeeTimeEntries.entryDate })
    .from(employeeTimeEntries)
    .where(
      and(
        eq(employeeTimeEntries.userId, userId),
        eq(employeeTimeEntries.entryType, "pause"),
        eq(employeeTimeEntries.isAutoGenerated, true),
        inArray(employeeTimeEntries.entryDate, allDates)
      )
    );

  const existingDates = new Set(existingAutoBreaks.map((e) => e.entryDate));

  const toInsert = breaks.filter((b) => !existingDates.has(b.date));
  if (toInsert.length === 0) return 0;

  await txOrDb.insert(employeeTimeEntries).values(
    toInsert.map((b) => ({
      userId,
      entryType: "pause" as const,
      entryDate: b.date,
      isFullDay: false,
      durationMinutes: b.autoBreakMinutes,
      isAutoGenerated: true,
      notes: `Automatische Pause gem. §4 ArbZG (${b.autoBreakMinutes} Min. bei ${Math.round((b.totalWorkMinutes / 60) * 10) / 10}h Arbeitszeit)`,
    }))
  );

  return toInsert.length;
}

export async function previewAutoBreaksForMonth(
  userId: number,
  year: number,
  month: number
): Promise<AutoBreakResult[]> {
  return generateAutoBreaksForMonth(userId, year, month);
}

export async function removeAutoBreaksForMonth(
  userId: number,
  year: number,
  month: number
): Promise<number> {
  const monthStr = month.toString().padStart(2, "0");
  const startDate = `${year}-${monthStr}-01`;
  const lastDay = new Date(year, month, 0).getDate();
  const endDate = `${year}-${monthStr}-${lastDay.toString().padStart(2, "0")}`;

  const deleted = await db
    .update(employeeTimeEntries)
    .set({ deletedAt: new Date() })
    .where(
      and(
        eq(employeeTimeEntries.userId, userId),
        gte(employeeTimeEntries.entryDate, startDate),
        lte(employeeTimeEntries.entryDate, endDate),
        eq(employeeTimeEntries.entryType, "pause"),
        eq(employeeTimeEntries.isAutoGenerated, true),
        sql`${employeeTimeEntries.deletedAt} IS NULL`
      )
    )
    .returning();

  return deleted.length;
}
