import { Button } from "@/components/ui/button";
import { Pencil, Trash2 } from "lucide-react";
import { iconSize } from "@/design-system";
import { TIME_ENTRY_TYPE_CONFIG } from "@/features/time-tracking/constants";
import type { TimeEntry, TimeEntryType } from "@/lib/api/types";

export function TimeEntryCard({
  entry,
  onEdit,
  onDelete,
  isMonthClosed,
}: {
  entry: TimeEntry;
  onEdit: (entry: TimeEntry) => void;
  onDelete: (entry: TimeEntry) => void;
  isMonthClosed: boolean;
}) {
  const config = TIME_ENTRY_TYPE_CONFIG[entry.entryType as TimeEntryType];
  if (!config) return null;
  const Icon = config.icon;
  const isAutoGenerated = entry.isAutoGenerated;
  const canModify = !isMonthClosed && !isAutoGenerated;

  return (
    <div
      className={`p-3 rounded-xl ${config.bgColor} flex items-center justify-between group`}
      data-testid={`time-entry-card-${entry.id}`}
    >
      <div className="flex items-center gap-3 min-w-0 flex-1">
        <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${config.bgColor} shrink-0`}>
          <Icon className={`${iconSize.md} ${config.color}`} />
        </div>
        <div className="min-w-0">
          <div className={`font-medium text-sm ${config.color} flex items-center gap-2`}>
            {config.label}
            {isAutoGenerated && (
              <span className="text-[10px] bg-gray-200 text-gray-600 px-1.5 py-0.5 rounded">Auto</span>
            )}
          </div>
          {entry.startTime && entry.endTime && (
            <div className="text-xs text-gray-500">
              {entry.startTime.slice(0, 5)} – {entry.endTime.slice(0, 5)}
            </div>
          )}
          {!entry.startTime && !entry.isFullDay && entry.durationMinutes && (
            <div className="text-xs text-gray-500">{entry.durationMinutes} Min.</div>
          )}
          {entry.isFullDay && !entry.startTime && (
            <div className="text-xs text-gray-500">Ganztägig</div>
          )}
          {entry.notes && (
            <div className="text-xs text-gray-500 truncate mt-0.5">{entry.notes}</div>
          )}
        </div>
      </div>
      {canModify && (
        <div className="flex items-center gap-0.5 shrink-0 ml-2">
          <Button
            variant="ghost"
            size="icon"
            className="h-11 w-11"
            onClick={() => onEdit(entry)}
            aria-label="Bearbeiten"
            data-testid={`button-edit-entry-${entry.id}`}
          >
            <Pencil className="h-4 w-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-11 w-11 text-red-600 hover:text-red-700 hover:bg-red-50"
            onClick={() => onDelete(entry)}
            aria-label="Löschen"
            data-testid={`button-delete-entry-${entry.id}`}
          >
            <Trash2 className="h-4 w-4" />
          </Button>
        </div>
      )}
    </div>
  );
}
