export const emptyCompanyForm = {
  companyName: "",
  geschaeftsfuehrer: "",
  strasse: "",
  hausnummer: "",
  plz: "",
  stadt: "",
  telefon: "",
  email: "",
  website: "",
  steuernummer: "",
  ustId: "",
  iban: "",
  bic: "",
  bankName: "",
  ikNummer: "",
  smtpHost: "",
  smtpPort: "",
  smtpUser: "",
  smtpPass: "",
  smtpFromEmail: "",
  smtpFromName: "",
  smtpSecure: false,
  letterxpressUsername: "",
  letterxpressApiKey: "",
  letterxpressTestMode: true,
  deliveryEmailSubject: "",
  deliveryCoverLetterText: "",
  qontoLogin: "",
  qontoSecretKey: "",
  qontoIban: "",
  twilioAccountSid: "",
  twilioAuthToken: "",
  twilioPhoneNumber: "",
  leadCallBridgePhone: "",
  leadCallBridgeEnabled: false,
  leadAutoReplyEnabled: false,
  leadAutoReplySubject: "",
  leadAutoReplyBody: "",
  leadAutoReplyAttachmentPath: "",
  leadAutoReplyAttachmentName: "",
};

export type CompanyFormData = typeof emptyCompanyForm;
