export const BUNDESLAENDER = [
  "Baden-Württemberg",
  "Bayern",
  "Berlin",
  "Brandenburg",
  "Bremen",
  "Hamburg",
  "Hessen",
  "Mecklenburg-Vorpommern",
  "Niedersachsen",
  "Nordrhein-Westfalen",
  "Rheinland-Pfalz",
  "Saarland",
  "Sachsen",
  "Sachsen-Anhalt",
  "Schleswig-Holstein",
  "Thüringen",
];

export const emptyCompanyForm = {
  companyName: "",
  geschaeftsfuehrer: "",
  strasse: "",
  hausnummer: "",
  plz: "",
  stadt: "",
  telefon: "",
  email: "",
  website: "",
  steuernummer: "",
  ustId: "",
  iban: "",
  bic: "",
  bankName: "",
  ikNummer: "",
  anerkennungsnummer45a: "",
  anerkennungsBundesland: "",
  smtpHost: "",
  smtpPort: "",
  smtpUser: "",
  smtpPass: "",
  smtpFromEmail: "",
  smtpFromName: "",
  smtpSecure: false,
  letterxpressUsername: "",
  letterxpressApiKey: "",
  letterxpressTestMode: true,
  deliveryEmailSubject: "",
  deliveryCoverLetterText: "",
  qontoLogin: "",
  qontoSecretKey: "",
  qontoIban: "",
  twilioAccountSid: "",
  twilioAuthToken: "",
  twilioPhoneNumber: "",
  leadCallBridgePhone: "",
  leadCallBridgeEnabled: false,
  leadAutoReplyEnabled: false,
  leadAutoReplySubject: "",
  leadAutoReplyBody: "",
  leadAutoReplyAttachmentPath: "",
  leadAutoReplyAttachmentName: "",
};

export type CompanyFormData = typeof emptyCompanyForm;
