import type { Appointment, EmployeeTimeEntry } from "../schema";

export type TimeEntryType =
  | "urlaub"
  | "krankheit"
  | "pause"
  | "bueroarbeit"
  | "vertrieb"
  | "sonstiges"
  | "verfuegbar"
  | "blocker";

export interface TimeEntry {
  id: number;
  userId: number;
  entryType: TimeEntryType;
  entryDate: string;
  startTime: string | null;
  endTime: string | null;
  isFullDay: boolean;
  durationMinutes: number | null;
  kilometers: number | null;
  notes: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface TimeEntryWithUser extends TimeEntry {
  user: {
    displayName: string;
  };
}

export interface CreateTimeEntryRequest {
  entryType: TimeEntryType;
  entryDate: string;
  endDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  isFullDay?: boolean;
  durationMinutes?: number | null;
  kilometers?: number | null;
  notes?: string | null;
  targetUserId?: number;
}

export interface UpdateTimeEntryRequest extends Partial<CreateTimeEntryRequest> {}

export interface VacationSummary {
  year: number;
  totalDays: number;
  carryOverDays: number;
  usedDays: number;
  plannedDays: number;
  remainingDays: number;
  sickDays: number;
}

interface AppointmentServiceBreakdown {
  serviceCode: string | null;
  plannedDurationMinutes: number;
  actualDurationMinutes: number | null;
}

export interface AppointmentWithCustomerName extends Appointment {
  customerName: string;
  services?: AppointmentServiceBreakdown[];
}

export interface ServiceHoursSummary {
  hauswirtschaftMinutes: number;
  alltagsbegleitungMinutes: number;
  erstberatungMinutes: number;
}

export interface TravelSummary {
  totalKilometers: number;
  customerKilometers: number;
  timeEntryKilometers: number;
  totalMinutes: number;
}

export interface TimeEntrySummary {
  urlaubDays: number;
  krankheitDays: number;
  pauseMinutes: number;
  bueroarbeitMinutes: number;
  vertriebMinutes: number;
  sonstigesMinutes: number;
}

export interface TimeOverviewData {
  period: { year: number; month: number };
  serviceHours: ServiceHoursSummary;
  completedServiceHours?: ServiceHoursSummary;
  plannedServiceHours?: ServiceHoursSummary;
  travel: TravelSummary;
  completedTravel?: Pick<TravelSummary, 'totalKilometers' | 'customerKilometers' | 'totalMinutes'>;
  plannedTravel?: Pick<TravelSummary, 'totalKilometers' | 'customerKilometers' | 'totalMinutes'>;
  timeEntries: TimeEntrySummary;
  appointments: AppointmentWithCustomerName[];
  otherEntries: EmployeeTimeEntry[];
}

export interface TimesPageData {
  overview: TimeOverviewData;
  vacationSummary: VacationSummary;
  openTasks: {
    daysWithMissingBreaks: Array<{
      date: string;
      totalWorkMinutes: number;
      requiredBreakMinutes: number;
      documentedBreakMinutes: number;
    }>;
  };
}
