import type { Appointment, EmployeeTimeEntry } from "../schema";

export type TimeEntryType =
  | "urlaub"
  | "krankheit"
  | "pause"
  | "bueroarbeit"
  | "vertrieb"
  | "sonstiges"
  | "verfuegbar"
  | "blocker";

export interface TimeEntry {
  id: number;
  userId: number;
  entryType: TimeEntryType;
  entryDate: string;
  startTime: string | null;
  endTime: string | null;
  isFullDay: boolean;
  durationMinutes: number | null;
  kilometers: number | null;
  notes: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface TimeEntryWithUser extends TimeEntry {
  user: {
    displayName: string;
  };
}

export interface CreateTimeEntryRequest {
  entryType: TimeEntryType;
  entryDate: string;
  endDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  isFullDay?: boolean;
  durationMinutes?: number | null;
  kilometers?: number | null;
  notes?: string | null;
  targetUserId?: number;
}

export interface UpdateTimeEntryRequest extends Partial<CreateTimeEntryRequest> {}

export interface VacationEntitlementHistoryItem {
  validFromYear: number;
  validFromMonth: number;
  daysPerYear: number;
}

export interface VacationMonthlyBreakdownItem {
  fromMonth: number;
  toMonth: number;
  daysPerYear: number;
}

export interface VacationSummary {
  year: number;
  /** Berechneter, anteiliger Jahresanspruch für `year`. */
  totalDays: number;
  /**
   * Aktuell konfigurierter Jahreswert (= `users.vacationDaysPerYear`,
   * gilt ab dem laufenden Monat).
   */
  configuredAnnualDays: number;
  /** Eintrittsdatum (für Live-Vorschau im Frontend benötigt). */
  eintrittsdatum: string | null;
  /** Wirksame History-Einträge des Mitarbeiters (Live-Vorschau). */
  entitlementHistory: VacationEntitlementHistoryItem[];
  /** Aufschlüsselung der Monats-Segmente für `year`. */
  monthlyBreakdown: VacationMonthlyBreakdownItem[];
  carryOverDays: number;
  usedDays: number;
  plannedDays: number;
  remainingDays: number;
  sickDays: number;
}

interface AppointmentServiceBreakdown {
  serviceCode: string | null;
  plannedDurationMinutes: number;
  actualDurationMinutes: number | null;
}

export interface AppointmentWithCustomerName extends Appointment {
  customerName: string;
  services?: AppointmentServiceBreakdown[];
  /**
   * Abgeleitetes Label aus `appointment_services` + `services.lohnart_kategorie`.
   * Siehe Hinweis bei `AppointmentWithCustomer.serviceType`.
   */
  serviceType: string | null;
}

export interface ServiceHoursSummary {
  hauswirtschaftMinutes: number;
  alltagsbegleitungMinutes: number;
  erstberatungMinutes: number;
}

export interface TravelSummary {
  totalKilometers: number;
  customerKilometers: number;
  timeEntryKilometers: number;
  totalMinutes: number;
}

export interface TimeEntrySummary {
  urlaubDays: number;
  krankheitDays: number;
  pauseMinutes: number;
  bueroarbeitMinutes: number;
  vertriebMinutes: number;
  sonstigesMinutes: number;
}

export interface TimeOverviewData {
  period: { year: number; month: number };
  serviceHours: ServiceHoursSummary;
  completedServiceHours?: ServiceHoursSummary;
  plannedServiceHours?: ServiceHoursSummary;
  travel: TravelSummary;
  completedTravel?: Pick<TravelSummary, 'totalKilometers' | 'customerKilometers' | 'totalMinutes'>;
  plannedTravel?: Pick<TravelSummary, 'totalKilometers' | 'customerKilometers' | 'totalMinutes'>;
  timeEntries: TimeEntrySummary;
  /**
   * Termine gruppiert nach Termin-Datum (`appointments.date` als ISO-String).
   * Server-seitige Gruppierung erspart dem Client einen `group-by-date`-Schritt.
   */
  appointments: Record<string, AppointmentWithCustomerName[]>;
  /**
   * Sonstige Zeit-Einträge (Pause, Urlaub, …) gruppiert nach `entryDate`.
   */
  otherEntries: Record<string, EmployeeTimeEntry[]>;
}

export interface AdminTimeTrackingOverview {
  entriesByEmployeeId: Record<number, TimeEntryWithUser[]>;
  appointmentsByEmployeeId: Record<number, AppointmentWithCustomerName[]>;
}

export interface TimesPageData {
  overview: TimeOverviewData;
  vacationSummary: VacationSummary;
  openTasks: {
    daysWithMissingBreaks: Array<{
      date: string;
      totalWorkMinutes: number;
      requiredBreakMinutes: number;
      documentedBreakMinutes: number;
    }>;
  };
}
